### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by sguzgon** [cometchat-pro-extensions/liftoff-js#1]
I installed Liftoff in an Ionic App but I have an initialization error. I have performed the steps described below:
`npm install @cometchat-pro/liftoff --save`

Package import:
`import { Liftoff } from '@cometchat-pro/liftoff';`

Initialization:
```
const appID = 'xxxxxxxxxxxxxx';

Liftoff.init(appID).then(
    () => {
        console.log('Application is initialized');
    },
    error => {
        console.log('Initialized failed with error:' + error);
    }
);
```

The error is described below:
> ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'init' of undefined
> TypeError: Cannot read property 'init' of undefined

**Comment by kshitizshakya** [comment]
Hello @sguzgon , 

Issue is resolved in v1.0.1. 
Please upgrade to v1.0.1 from npmjs.
